#server.port=443
#server.ssl.key-store=classpath:jishenghua.jks
#server.ssl.key-alias=alias
#server.ssl.key-store-password=M9z21aFp
#server.ssl.key-store-type=JKS
#ssl的开关

#登录超时-秒
server:
  servlet:
    session:
      timeout: 36000
  ssl:
    enable: false
#数据库连接
spring:
  datasource:
    url: jdbc:mysql://47.106.69.253:3306/hujiangerp?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: Hujiang666

project: src/main/java
resource: src/main/resources
web:
  front:
    baseDir: erp_web
mybatis:
  type-aliases-package: com.jsh.erp.datasource.entities.*
  mapper-locations: classpath:./mapper_xml/*.xml

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:./mapper_xml/*.xml
#租户对应的角色id
manage:
  roleId: 10

product:
  name: 测试ERP1
