
#登录超时-秒
server:
  servlet:
    session:
      timeout: 36000
  ssl:
    enable: false
#数据库连接
spring:
  datasource:
    url: jdbc:mysql://47.104.98.19:3306/jsh_erp?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: hrg_song
    password: Hrg_song123456

project: src/main/java
resource: src/main/resources
web:
  front:
    baseDir: erp_web
mybatis:
  type-aliases-package: com.jsh.erp.datasource.entities.*
  mapper-locations: classpath:./mapper_xml/*.xml

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:./mapper_xml/*.xml
#租户对应的角色id
manage:
  roleId: 10
product:
  name: ERP
