package com.jsh.erp.datasource.entities;

import java.math.BigDecimal;

public class DepotItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.HeaderId
     *
     * @mbggenerated
     */
    private Long headerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.MaterialId
     *
     * @mbggenerated
     */
    private Long materialid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.MUnit
     *
     * @mbggenerated
     */
    private String munit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.OperNumber
     *
     * @mbggenerated
     */
    private BigDecimal opernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.BasicNumber
     *
     * @mbggenerated
     */
    private BigDecimal basicnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.UnitPrice
     *
     * @mbggenerated
     */
    private BigDecimal unitprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.TaxUnitPrice
     *
     * @mbggenerated
     */
    private BigDecimal taxunitprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.AllPrice
     *
     * @mbggenerated
     */
    private BigDecimal allprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.Remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.Img
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.Incidentals
     *
     * @mbggenerated
     */
    private BigDecimal incidentals;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.DepotId
     *
     * @mbggenerated
     */
    private Long depotid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.AnotherDepotId
     *
     * @mbggenerated
     */
    private Long anotherdepotid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.TaxRate
     *
     * @mbggenerated
     */
    private BigDecimal taxrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.TaxMoney
     *
     * @mbggenerated
     */
    private BigDecimal taxmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.TaxLastMoney
     *
     * @mbggenerated
     */
    private BigDecimal taxlastmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.OtherField1
     *
     * @mbggenerated
     */
    private String otherfield1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.OtherField2
     *
     * @mbggenerated
     */
    private String otherfield2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.OtherField3
     *
     * @mbggenerated
     */
    private String otherfield3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.OtherField4
     *
     * @mbggenerated
     */
    private String otherfield4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.OtherField5
     *
     * @mbggenerated
     */
    private String otherfield5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.MType
     *
     * @mbggenerated
     */
    private String mtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.tenant_id
     *
     * @mbggenerated
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.delete_Flag
     *
     * @mbggenerated
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.we_chat
     *
     * @mbggenerated
     */
    private String we_chat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.contacts_name
     *
     * @mbggenerated
     */
    private String contacts_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.contacts_phone
     *
     * @mbggenerated
     */
    private String contacts_phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.project_address
     *
     * @mbggenerated
     */
    private String project_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.project_name
     *
     * @mbggenerated
     */
    private String project_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.card_ognizer
     *
     * @mbggenerated
     */
    private String card_ognizer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.ognizer_number
     *
     * @mbggenerated
     */
    private String ognizer_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.contract
     *
     * @mbggenerated
     */
    private String contract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.conyract_number
     *
     * @mbggenerated
     */
    private String conyract_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.conyract_money
     *
     * @mbggenerated
     */
    private String conyract_money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.payment
     *
     * @mbggenerated
     */
    private String payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.invoice
     *
     * @mbggenerated
     */
    private String invoice;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.install
     *
     * @mbggenerated
     */
    private String install;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.installer
     *
     * @mbggenerated
     */
    private String installer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.installer_time
     *
     * @mbggenerated
     */
    private String installer_time;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.machine
     *
     * @mbggenerated
     */
    private String machine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.machine_type
     *
     * @mbggenerated
     */
    private String machine_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.machine_number
     *
     * @mbggenerated
     */
    private String machine_number;

    private int machine_number2;

    private Long machinetype_id;

    private Long gatetype_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.gate
     *
     * @mbggenerated
     */
    private String gate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.gate_type
     *
     * @mbggenerated
     */
    private String gate_type;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.gate_number
     *
     * @mbggenerated
     */
    private String gate_number;

    private int gate_number2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.order_type
     *
     * @mbggenerated
     */
    private String order_type;

    private String OrganName;
    private String contacts;
    private String phonenum;
    private String description;

    public String getDescription(){
        return description;
    }
    public void setDescription(String description){
        this.description = description;
    }

    public String getPhonenum(){
        return phonenum;
    }
    public void setPhonenum(String phonenum){
        this.phonenum = phonenum;
    }
    public String getContacts(){
        return contacts;
    }
    public void setContacts(String contacts){
        this.contacts = contacts;
    }
    public String getOrganName(){
        return OrganName;
    }
    public void setOrganName(String OrganName){
        this.OrganName = OrganName;
    }

    public Long getMachinetype_id() {
        return machinetype_id;
    }

    public void setMachinetype_id(Long machinetype_id) {
        this.machinetype_id = machinetype_id;
    }

    public Long getGatetype_id() {
        return gatetype_id;
    }

    public void setGatetype_id(Long gatetype_id) {
        this.gatetype_id = gatetype_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.order_type
     *
     * @return the value of jsh_depotitem.order_type
     *
     * @mbggenerated
     */
    public String getOrder_type() {
        return order_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.order_type
     *
     * @param order_type the value for jsh_depotitem.order_type
     *
     * @mbggenerated
     */
    public void setOrder_type(String order_type) { this.order_type = order_type; }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.gate_type
     *
     * @return the value of jsh_depotitem.gate_type
     *
     * @mbggenerated
     */
    public String getGate_type() {
        return gate_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.gate_type
     *
     * @param gate_type the value for jsh_depotitem.gate_type
     *
     * @mbggenerated
     */
    public void setGate_type(String gate_type) { this.gate_type = gate_type; }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.gate_number
     *
     * @return the value of jsh_depotitem.gate_number
     *
     * @mbggenerated
     */
    public String getGate_number() {
        return gate_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.gate_number
     *
     * @param gate_number the value for jsh_depotitem.gate_number
     *
     * @mbggenerated
     */
    public void setGate_number(String gate_number) { this.gate_number = gate_number; }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.gate
     *
     * @return the value of jsh_depotitem.gate
     *
     * @mbggenerated
     */
    public String getGate() {
        return gate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.gate
     *
     * @param gate the value for jsh_depotitem.gate
     *
     * @mbggenerated
     */
    public void setGate(String gate) { this.gate = gate; }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.machine_type
     *
     * @return the value of jsh_depotitem.machine_type
     *
     * @mbggenerated
     */
    public String getMachine_type() {
        return machine_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.machine_type
     *
     * @param machine_type the value for jsh_depotitem.machine_type
     *
     * @mbggenerated
     */
    public void setMachine_type(String machine_type) { this.machine_type = machine_type; }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.machine_number
     *
     * @return the value of jsh_depotitem.machine_number
     *
     * @mbggenerated
     */
    public String getMachine_number() {
        return machine_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.machine_number
     *
     * @param machine_number the value for jsh_depotitem.machine_number
     *
     * @mbggenerated
     */
    public void setMachine_number(String machine_number) { this.machine_number = machine_number; }




    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.machine
     *
     * @return the value of jsh_depotitem.machine
     *
     * @mbggenerated
     */
    public String getMachine() {
        return machine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.machine
     *
     * @param machine the value for jsh_depotitem.machine
     *
     * @mbggenerated
     */
    public void setMachine(String machine) { this.machine = machine; }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.installer_time
     *
     * @return the value of jsh_depotitem.installer_time
     *
     * @mbggenerated
     */
    public String getInstaller_time() {
        return installer_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.installer_time
     *
     * @param installer_time the value for jsh_depotitem.installer_time
     *
     * @mbggenerated
     */
    public void setInstaller_time(String installer_time) { this.installer_time = installer_time; }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.installer
     *
     * @return the value of jsh_depotitem.installer
     *
     * @mbggenerated
     */
    public String getInstaller() {
        return installer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.installer
     *
     * @param installer the value for jsh_depotitem.installer
     *
     * @mbggenerated
     */
    public void setInstaller(String installer) { this.installer = installer; }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.install
     *
     * @return the value of jsh_depotitem.install
     *
     * @mbggenerated
     */
    public String getInstall() {
        return install;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.install
     *
     * @param install the value for jsh_depotitem.install
     *
     * @mbggenerated
     */
    public void setInstall(String install) { this.install = install; }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.invoice
     *
     * @return the value of jsh_depotitem.invoice
     *
     * @mbggenerated
     */
    public String getInvoice() {
        return invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.invoice
     *
     * @param invoice the value for jsh_depotitem.invoice
     *
     * @mbggenerated
     */
    public void setInvoice(String invoice) { this.invoice = invoice; }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.payment
     *
     * @return the value of jsh_depotitem.payment
     *
     * @mbggenerated
     */
    public String getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.payment
     *
     * @param payment the value for jsh_depotitem.payment
     *
     * @mbggenerated
     */
    public void setPayment(String payment) { this.payment = payment; }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.conyract_money
     *
     * @return the value of jsh_depotitem.conyract_money
     *
     * @mbggenerated
     */
    public String getConyract_money() {
        return conyract_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.conyract_money
     *
     * @param conyract_money the value for jsh_depotitem.conyract_money
     *
     * @mbggenerated
     */
    public void setConyract_money(String conyract_money) { this.conyract_money = conyract_money; }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.conyract_number
     *
     * @return the value of jsh_depotitem.conyract_number
     *
     * @mbggenerated
     */
    public String getConyract_number() {
        return conyract_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.conyract_number
     *
     * @param conyract_number the value for jsh_depotitem.conyract_number
     *
     * @mbggenerated
     */
    public void setConyract_number(String conyract_number) { this.conyract_number = conyract_number; }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.contract
     *
     * @return the value of jsh_depotitem.contract
     *
     * @mbggenerated
     */
    public String getContract() {
        return contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.contract
     *
     * @param contract the value for jsh_depotitem.contract
     *
     * @mbggenerated
     */
    public void setContract(String contract) { this.contract = contract; }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.ognizer_number
     *
     * @return the value of jsh_depotitem.ognizer_number
     *
     * @mbggenerated
     */
    public String getOgnizer_number() {
        return ognizer_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.ognizer_number
     *
     * @param ognizer_number the value for jsh_depotitem.ognizer_number
     *
     * @mbggenerated
     */
    public void setOgnizer_number(String ognizer_number) { this.ognizer_number = ognizer_number; }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.card_ognizer
     *
     * @return the value of jsh_depotitem.card_ognizer
     *
     * @mbggenerated
     */
    public String getCard_ognizer() {
        return card_ognizer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.card_ognizer
     *
     * @param card_ognizer the value for jsh_depotitem.card_ognizer
     *
     * @mbggenerated
     */
    public void setCard_ognizer(String card_ognizer) { this.card_ognizer = card_ognizer; }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.project_address
     *
     * @return the value of jsh_depotitem.project_address
     *
     * @mbggenerated
     */
    public String getProject_name() {
        return project_name;
    }


    public int getMachine_number2() {
        return machine_number2;
    }

    public void setMachine_number2(int machine_number2) {
        this.machine_number2 = machine_number2;
    }

    public int getGate_number2() {
        return gate_number2;
    }

    public void setGate_number2(int gate_number2) {
        this.gate_number2 = gate_number2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.project_name
     *
     * @param project_name the value for jsh_depotitem.project_name
     *
     * @mbggenerated
     */
    public void setProject_name(String project_name) { this.project_name = project_name; }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.project_address
     *
     * @return the value of jsh_depotitem.project_address
     *
     * @mbggenerated
     */
    public String getProject_address() {
        return project_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.project_address
     *
     * @param project_address the value for jsh_depotitem.project_address
     *
     * @mbggenerated
     */
    public void setProject_address(String project_address) { this.project_address = project_address; }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.company
     *
     * @return the value of jsh_depotitem.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.company
     *
     * @param company the value for jsh_depotitem.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.contacts_phone
     *
     * @return the value of jsh_depotitem.contacts_phone
     *
     * @mbggenerated
     */
    public String getContacts_phone() {
        return contacts_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.contacts_phone
     *
     * @param contacts_phone the value for jsh_depotitem.contacts_phone
     *
     * @mbggenerated
     */
    public void setContacts_phone(String contacts_phone) {
        this.contacts_phone = contacts_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.contacts_name
     *
     * @return the value of jsh_depotitem.contacts_name
     *
     * @mbggenerated
     */
    public String getContacts_name() {
        return contacts_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.contacts_name
     *
     * @param contacts_name the value for jsh_depotitem.contacts_name
     *
     * @mbggenerated
     */
    public void setContacts_name(String contacts_name) {
        this.contacts_name = contacts_name;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.we_chat
     *
     * @return the value of jsh_depotitem.we_chat
     *
     * @mbggenerated
     */
    public String getWe_chat() {
        return we_chat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.we_chat
     *
     * @param we_chat the value for jsh_depotitem.we_chat
     *
     * @mbggenerated
     */
    public void setWe_chat(String we_chat) {
        this.we_chat = we_chat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.Id
     *
     * @return the value of jsh_depotitem.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.Id
     *
     * @param id the value for jsh_depotitem.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.HeaderId
     *
     * @return the value of jsh_depotitem.HeaderId
     *
     * @mbggenerated
     */
    public Long getHeaderid() {
        return headerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.HeaderId
     *
     * @param headerid the value for jsh_depotitem.HeaderId
     *
     * @mbggenerated
     */
    public void setHeaderid(Long headerid) {
        this.headerid = headerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.MaterialId
     *
     * @return the value of jsh_depotitem.MaterialId
     *
     * @mbggenerated
     */
    public Long getMaterialid() {
        return materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.MaterialId
     *
     * @param materialid the value for jsh_depotitem.MaterialId
     *
     * @mbggenerated
     */
    public void setMaterialid(Long materialid) {
        this.materialid = materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.MUnit
     *
     * @return the value of jsh_depotitem.MUnit
     *
     * @mbggenerated
     */
    public String getMunit() {
        return munit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.MUnit
     *
     * @param munit the value for jsh_depotitem.MUnit
     *
     * @mbggenerated
     */
    public void setMunit(String munit) {
        this.munit = munit == null ? null : munit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.OperNumber
     *
     * @return the value of jsh_depotitem.OperNumber
     *
     * @mbggenerated
     */
    public BigDecimal getOpernumber() {
        return opernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.OperNumber
     *
     * @param opernumber the value for jsh_depotitem.OperNumber
     *
     * @mbggenerated
     */
    public void setOpernumber(BigDecimal opernumber) {
        this.opernumber = opernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.BasicNumber
     *
     * @return the value of jsh_depotitem.BasicNumber
     *
     * @mbggenerated
     */
    public BigDecimal getBasicnumber() {
        return basicnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.BasicNumber
     *
     * @param basicnumber the value for jsh_depotitem.BasicNumber
     *
     * @mbggenerated
     */
    public void setBasicnumber(BigDecimal basicnumber) {
        this.basicnumber = basicnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.UnitPrice
     *
     * @return the value of jsh_depotitem.UnitPrice
     *
     * @mbggenerated
     */
    public BigDecimal getUnitprice() {
        return unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.UnitPrice
     *
     * @param unitprice the value for jsh_depotitem.UnitPrice
     *
     * @mbggenerated
     */
    public void setUnitprice(BigDecimal unitprice) {
        this.unitprice = unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.TaxUnitPrice
     *
     * @return the value of jsh_depotitem.TaxUnitPrice
     *
     * @mbggenerated
     */
    public BigDecimal getTaxunitprice() {
        return taxunitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.TaxUnitPrice
     *
     * @param taxunitprice the value for jsh_depotitem.TaxUnitPrice
     *
     * @mbggenerated
     */
    public void setTaxunitprice(BigDecimal taxunitprice) {
        this.taxunitprice = taxunitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.AllPrice
     *
     * @return the value of jsh_depotitem.AllPrice
     *
     * @mbggenerated
     */
    public BigDecimal getAllprice() {
        return allprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.AllPrice
     *
     * @param allprice the value for jsh_depotitem.AllPrice
     *
     * @mbggenerated
     */
    public void setAllprice(BigDecimal allprice) {
        this.allprice = allprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.Remark
     *
     * @return the value of jsh_depotitem.Remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.Remark
     *
     * @param remark the value for jsh_depotitem.Remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.Img
     *
     * @return the value of jsh_depotitem.Img
     *
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.Img
     *
     * @param img the value for jsh_depotitem.Img
     *
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.Incidentals
     *
     * @return the value of jsh_depotitem.Incidentals
     *
     * @mbggenerated
     */
    public BigDecimal getIncidentals() {
        return incidentals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.Incidentals
     *
     * @param incidentals the value for jsh_depotitem.Incidentals
     *
     * @mbggenerated
     */
    public void setIncidentals(BigDecimal incidentals) {
        this.incidentals = incidentals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.DepotId
     *
     * @return the value of jsh_depotitem.DepotId
     *
     * @mbggenerated
     */
    public Long getDepotid() {
        return depotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.DepotId
     *
     * @param depotid the value for jsh_depotitem.DepotId
     *
     * @mbggenerated
     */
    public void setDepotid(Long depotid) {
        this.depotid = depotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.AnotherDepotId
     *
     * @return the value of jsh_depotitem.AnotherDepotId
     *
     * @mbggenerated
     */
    public Long getAnotherdepotid() {
        return anotherdepotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.AnotherDepotId
     *
     * @param anotherdepotid the value for jsh_depotitem.AnotherDepotId
     *
     * @mbggenerated
     */
    public void setAnotherdepotid(Long anotherdepotid) {
        this.anotherdepotid = anotherdepotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.TaxRate
     *
     * @return the value of jsh_depotitem.TaxRate
     *
     * @mbggenerated
     */
    public BigDecimal getTaxrate() {
        return taxrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.TaxRate
     *
     * @param taxrate the value for jsh_depotitem.TaxRate
     *
     * @mbggenerated
     */
    public void setTaxrate(BigDecimal taxrate) {
        this.taxrate = taxrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.TaxMoney
     *
     * @return the value of jsh_depotitem.TaxMoney
     *
     * @mbggenerated
     */
    public BigDecimal getTaxmoney() {
        return taxmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.TaxMoney
     *
     * @param taxmoney the value for jsh_depotitem.TaxMoney
     *
     * @mbggenerated
     */
    public void setTaxmoney(BigDecimal taxmoney) {
        this.taxmoney = taxmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.TaxLastMoney
     *
     * @return the value of jsh_depotitem.TaxLastMoney
     *
     * @mbggenerated
     */
    public BigDecimal getTaxlastmoney() {
        return taxlastmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.TaxLastMoney
     *
     * @param taxlastmoney the value for jsh_depotitem.TaxLastMoney
     *
     * @mbggenerated
     */
    public void setTaxlastmoney(BigDecimal taxlastmoney) {
        this.taxlastmoney = taxlastmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.OtherField1
     *
     * @return the value of jsh_depotitem.OtherField1
     *
     * @mbggenerated
     */
    public String getOtherfield1() {
        return otherfield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.OtherField1
     *
     * @param otherfield1 the value for jsh_depotitem.OtherField1
     *
     * @mbggenerated
     */
    public void setOtherfield1(String otherfield1) {
        this.otherfield1 = otherfield1 == null ? null : otherfield1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.OtherField2
     *
     * @return the value of jsh_depotitem.OtherField2
     *
     * @mbggenerated
     */
    public String getOtherfield2() {
        return otherfield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.OtherField2
     *
     * @param otherfield2 the value for jsh_depotitem.OtherField2
     *
     * @mbggenerated
     */
    public void setOtherfield2(String otherfield2) {
        this.otherfield2 = otherfield2 == null ? null : otherfield2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.OtherField3
     *
     * @return the value of jsh_depotitem.OtherField3
     *
     * @mbggenerated
     */
    public String getOtherfield3() {
        return otherfield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.OtherField3
     *
     * @param otherfield3 the value for jsh_depotitem.OtherField3
     *
     * @mbggenerated
     */
    public void setOtherfield3(String otherfield3) {
        this.otherfield3 = otherfield3 == null ? null : otherfield3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.OtherField4
     *
     * @return the value of jsh_depotitem.OtherField4
     *
     * @mbggenerated
     */
    public String getOtherfield4() {
        return otherfield4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.OtherField4
     *
     * @param otherfield4 the value for jsh_depotitem.OtherField4
     *
     * @mbggenerated
     */
    public void setOtherfield4(String otherfield4) {
        this.otherfield4 = otherfield4 == null ? null : otherfield4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.OtherField5
     *
     * @return the value of jsh_depotitem.OtherField5
     *
     * @mbggenerated
     */
    public String getOtherfield5() {
        return otherfield5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.OtherField5
     *
     * @param otherfield5 the value for jsh_depotitem.OtherField5
     *
     * @mbggenerated
     */
    public void setOtherfield5(String otherfield5) {
        this.otherfield5 = otherfield5 == null ? null : otherfield5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.MType
     *
     * @return the value of jsh_depotitem.MType
     *
     * @mbggenerated
     */
    public String getMtype() {
        return mtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.MType
     *
     * @param mtype the value for jsh_depotitem.MType
     *
     * @mbggenerated
     */
    public void setMtype(String mtype) {
        this.mtype = mtype == null ? null : mtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.tenant_id
     *
     * @return the value of jsh_depotitem.tenant_id
     *
     * @mbggenerated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.tenant_id
     *
     * @param tenantId the value for jsh_depotitem.tenant_id
     *
     * @mbggenerated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.delete_Flag
     *
     * @return the value of jsh_depotitem.delete_Flag
     *
     * @mbggenerated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.delete_Flag
     *
     * @param deleteFlag the value for jsh_depotitem.delete_Flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }
}