package com.jsh.erp.datasource.entities;

import java.math.BigDecimal;
import java.util.Date;

public class DepotHead {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.Type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.SubType
     *
     * @mbggenerated
     */
    private String subtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.ProjectId
     *
     * @mbggenerated
     */
    private Long projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.DefaultNumber
     *
     * @mbggenerated
     */
    private String defaultnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.Number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.OperPersonName
     *
     * @mbggenerated
     */
    private String operpersonname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.gateNumber
     *
     * @mbggenerated
     */
    private String gatenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.OperTime
     *
     * @mbggenerated
     */
    private Date opertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.OrganId
     *
     * @mbggenerated
     */
    private Long organid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.HandsPersonId
     *
     * @mbggenerated
     */
    private Long handspersonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.AccountId
     *
     * @mbggenerated
     */
    private Long accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.ChangeAmount
     *
     * @mbggenerated
     */
    private BigDecimal changeamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.AllocationProjectId
     *
     * @mbggenerated
     */
    private Long allocationprojectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.TotalPrice
     *
     * @mbggenerated
     */
    private BigDecimal totalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.PayType
     *
     * @mbggenerated
     */
    private String paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.Remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.Salesman
     *
     * @mbggenerated
     */
    private String salesman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.AccountIdList
     *
     * @mbggenerated
     */
    private String accountidlist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.AccountMoneyList
     *
     * @mbggenerated
     */
    private String accountmoneylist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.Discount
     *
     * @mbggenerated
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.DiscountMoney
     *
     * @mbggenerated
     */
    private BigDecimal discountmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.DiscountLastMoney
     *
     * @mbggenerated
     */
    private BigDecimal discountlastmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.OtherMoney
     *
     * @mbggenerated
     */
    private BigDecimal othermoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.OtherMoneyList
     *
     * @mbggenerated
     */
    private String othermoneylist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.OtherMoneyItem
     *
     * @mbggenerated
     */
    private String othermoneyitem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.AccountDay
     *
     * @mbggenerated
     */
    private Integer accountday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.Status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.LinkNumber
     *
     * @mbggenerated
     */
    private String linknumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.tenant_id
     *
     * @mbggenerated
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.delete_Flag
     *
     * @mbggenerated
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.we_chat
     *
     * @mbggenerated
     */
    private String we_chat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.contacts_name
     *
     * @mbggenerated
     */
    private String contacts_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.contacts_phone
     *
     * @mbggenerated
     */
    private String contacts_phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.project_address
     *
     * @mbggenerated
     */
    private String project_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.project_name
     *
     * @mbggenerated
     */
    private String project_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.card_ognizer
     *
     * @mbggenerated
     */
    private String card_ognizer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.ognizer_number
     *
     * @mbggenerated
     */
    private String ognizer_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.contract
     *
     * @mbggenerated
     */
    private String contract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.conyract_number
     *
     * @mbggenerated
     */
    private String conyract_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.conyract_money
     *
     * @mbggenerated
     */
    private String conyract_money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.payment
     *
     * @mbggenerated
     */
    private String payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.invoice
     *
     * @mbggenerated
     */
    private String invoice;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.install
     *
     * @mbggenerated
     */
    private String install;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.installer
     *
     * @mbggenerated
     */
    private String installer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.installer_time
     *
     * @mbggenerated
     */
    private String installer_time;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.machine
     *
     * @mbggenerated
     */
    private String machine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.machine_type
     *
     * @mbggenerated
     */
    private String machine_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.machine_number
     *
     * @mbggenerated
     */
    private String machine_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.gate
     *
     * @mbggenerated
     */
    private String gate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.gate_type
     *
     * @mbggenerated
     */
    private String gate_type;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.gate_number
     *
     * @mbggenerated
     */
    private String gate_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.order_type
     *
     * @mbggenerated
     */
    private String order_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.operNumber
     *
     * @mbggenerated
     */
    private Double operNumber;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.operTimes
     *
     * @mbggenerated
     */
    private String operTimes;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.invoice_number
     *
     * @mbggenerated
     */
    private String invoice_number;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depothead.invoice_date
     *
     * @mbggenerated
     */
    private String invoice_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.invoice_date
     *
     * @return the value of jsh_depothead.invoice_date
     *
     * @mbggenerated
     */
    public String getInvoice_date() {
        return invoice_date;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.invoice_date
     *
     * @param invoice_date the value for jsh_depothead.invoice_date
     *
     * @mbggenerated
     */
    public void setInvoice_date(String invoice_date) {
        this.invoice_date = invoice_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.invoice_number
     *
     * @return the value of jsh_depothead.invoice_number
     *
     * @mbggenerated
     */
    public String getInvoice_number() {
        return invoice_number;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.invoice_number
     *
     * @param invoice_number the value for jsh_depothead.invoice_number
     *
     * @mbggenerated
     */
    public void setInvoice_number(String invoice_number) {
        this.invoice_number = invoice_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.operTimes
     *
     * @return the value of jsh_depothead.operTimes
     *
     * @mbggenerated
     */
    public String getOperTimes() {
        return operTimes;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.operTimes
     *
     * @param operTimes the value for jsh_depothead.operTimes
     *
     * @mbggenerated
     */
    public void setOperTimes(String operTimes) {
        this.operTimes = operTimes;
    }


    public void setGatenumber(String gatenumber) {
        this.gatenumber = gatenumber == null ? null : gatenumber.trim();
    }

    public String getGatenumber() {
        return gatenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.operNumber
     *
     * @return the value of jsh_depothead.operNumber
     *
     * @mbggenerated
     */
    public Double getOperNumber() {
        return operNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.operNumber
     *
     * @param operNumber the value for jsh_depothead.operNumber
     *
     * @mbggenerated
     */
    public void setOperNumber(Double operNumber) { this.operNumber = operNumber; }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.order_type
     *
     * @return the value of jsh_depothead.order_type
     *
     * @mbggenerated
     */
    public String getOrder_type() {
        return order_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.order_type
     *
     * @param order_type the value for jsh_depothead.order_type
     *
     * @mbggenerated
     */
    public void setOrder_type(String order_type) { this.order_type = order_type == null ? null : order_type.trim(); }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.gate_type
     *
     * @return the value of jsh_depothead.gate_type
     *
     * @mbggenerated
     */
    public String getGate_type() {
        return gate_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.gate_type
     *
     * @param gate_type the value for jsh_depothead.gate_type
     *
     * @mbggenerated
     */
    public void setGate_type(String gate_type) { this.gate_type = gate_type == null ? null : gate_type.trim(); }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.gate_number
     *
     * @return the value of jsh_depothead.gate_number
     *
     * @mbggenerated
     */
    public String getGate_number() {
        return gate_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.gate_number
     *
     * @param gate_number the value for jsh_depothead.gate_number
     *
     * @mbggenerated
     */
    public void setGate_number(String gate_number) { this.gate_number = gate_number == null ? null : gate_number.trim(); }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.gate
     *
     * @return the value of jsh_depothead.gate
     *
     * @mbggenerated
     */
    public String getGate() {
        return gate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.gate
     *
     * @param gate the value for jsh_depothead.gate
     *
     * @mbggenerated
     */
    public void setGate(String gate) { this.gate = gate == null ? null : gate.trim(); }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.machine_type
     *
     * @return the value of jsh_depothead.machine_type
     *
     * @mbggenerated
     */
    public String getMachine_type() {
        return machine_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.machine_type
     *
     * @param machine_type the value for jsh_depothead.machine_type
     *
     * @mbggenerated
     */
    public void setMachine_type(String machine_type) { this.machine_type = machine_type == null ? null : machine_type.trim(); }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.machine_number
     *
     * @return the value of jsh_depothead.machine_number
     *
     * @mbggenerated
     */
    public String getMachine_number() {
        return machine_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.machine_number
     *
     * @param machine_number the value for jsh_depothead.machine_number
     *
     * @mbggenerated
     */
    public void setMachine_number(String machine_number) { this.machine_number = machine_number == null ? null : machine_number.trim(); }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.machine
     *
     * @return the value of jsh_depothead.machine
     *
     * @mbggenerated
     */
    public String getMachine() {
        return machine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.machine
     *
     * @param machine the value for jsh_depothead.machine
     *
     * @mbggenerated
     */
    public void setMachine(String machine) { this.machine = machine == null ? null : machine.trim(); }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.installer_time
     *
     * @return the value of jsh_depothead.installer_time
     *
     * @mbggenerated
     */
    public String getInstaller_time() {
        return installer_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.installer_time
     *
     * @param installer_time the value for jsh_depothead.installer_time
     *
     * @mbggenerated
     */
    public void setInstaller_time(String installer_time) { this.installer_time = installer_time == null ? null : installer_time.trim(); }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.installer
     *
     * @return the value of jsh_depothead.installer
     *
     * @mbggenerated
     */
    public String getInstaller() {
        return installer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.installer
     *
     * @param installer the value for jsh_depothead.installer
     *
     * @mbggenerated
     */
    public void setInstaller(String installer) { this.installer = installer == null ? null : installer.trim(); }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.install
     *
     * @return the value of jsh_depothead.install
     *
     * @mbggenerated
     */
    public String getInstall() {
        return install;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.install
     *
     * @param install the value for jsh_depothead.install
     *
     * @mbggenerated
     */
    public void setInstall(String install) { this.install = install == null ? null : install.trim(); }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.invoice
     *
     * @return the value of jsh_depothead.invoice
     *
     * @mbggenerated
     */
    public String getInvoice() {
        return invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.invoice
     *
     * @param invoice the value for jsh_depothead.invoice
     *
     * @mbggenerated
     */
    public void setInvoice(String invoice) { this.invoice = invoice == null ? null : invoice.trim(); }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.payment
     *
     * @return the value of jsh_depothead.payment
     *
     * @mbggenerated
     */
    public String getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.payment
     *
     * @param payment the value for jsh_depothead.payment
     *
     * @mbggenerated
     */
    public void setPayment(String payment) { this.payment = payment == null ? null : payment.trim(); }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.conyract_money
     *
     * @return the value of jsh_depothead.conyract_money
     *
     * @mbggenerated
     */
    public String getConyract_money() {
        return conyract_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.conyract_money
     *
     * @param conyract_money the value for jsh_depothead.conyract_money
     *
     * @mbggenerated
     */
    public void setConyract_money(String conyract_money) { this.conyract_money = conyract_money == null ? null : conyract_money.trim(); }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.conyract_number
     *
     * @return the value of jsh_depothead.conyract_number
     *
     * @mbggenerated
     */
    public String getConyract_number() {
        return conyract_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.conyract_number
     *
     * @param conyract_number the value for jsh_depothead.conyract_number
     *
     * @mbggenerated
     */
    public void setConyract_number(String conyract_number) { this.conyract_number = conyract_number == null ? null : conyract_number.trim(); }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.contract
     *
     * @return the value of jsh_depothead.contract
     *
     * @mbggenerated
     */
    public String getContract() {
        return contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.contract
     *
     * @param contract the value for jsh_depothead.contract
     *
     * @mbggenerated
     */
    public void setContract(String contract) { this.contract = contract == null ? null : contract.trim(); }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.ognizer_number
     *
     * @return the value of jsh_depothead.ognizer_number
     *
     * @mbggenerated
     */
    public String getOgnizer_number() {
        return ognizer_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.ognizer_number
     *
     * @param ognizer_number the value for jsh_depothead.ognizer_number
     *
     * @mbggenerated
     */
    public void setOgnizer_number(String ognizer_number) { this.ognizer_number = ognizer_number == null ? null : ognizer_number.trim(); }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.card_ognizer
     *
     * @return the value of jsh_depothead.card_ognizer
     *
     * @mbggenerated
     */
    public String getCard_ognizer() {
        return card_ognizer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.card_ognizer
     *
     * @param card_ognizer the value for jsh_depothead.card_ognizer
     *
     * @mbggenerated
     */
    public void setCard_ognizer(String card_ognizer) { this.card_ognizer = card_ognizer == null ? null : card_ognizer.trim(); }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.project_address
     *
     * @return the value of jsh_depothead.project_address
     *
     * @mbggenerated
     */
    public String getProject_name() {
        return project_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.project_name
     *
     * @param project_name the value for jsh_depothead.project_name
     *
     * @mbggenerated
     */
    public void setProject_name(String project_name) { this.project_name = project_name == null ? null : project_name.trim(); }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.project_address
     *
     * @return the value of jsh_depothead.project_address
     *
     * @mbggenerated
     */
    public String getProject_address() {
        return project_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.project_address
     *
     * @param project_address the value for jsh_depothead.project_address
     *
     * @mbggenerated
     */
    public void setProject_address(String project_address) { this.project_address = project_address == null ? null : project_address.trim(); }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.company
     *
     * @return the value of jsh_depothead.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.company
     *
     * @param company the value for jsh_depothead.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.contacts_phone
     *
     * @return the value of jsh_depothead.contacts_phone
     *
     * @mbggenerated
     */
    public String getContacts_phone() {
        return contacts_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.contacts_phone
     *
     * @param contacts_phone the value for jsh_depothead.contacts_phone
     *
     * @mbggenerated
     */
    public void setContacts_phone(String contacts_phone) {
        this.contacts_phone = contacts_phone == null ? null : contacts_phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.contacts_name
     *
     * @return the value of jsh_depothead.contacts_name
     *
     * @mbggenerated
     */
    public String getContacts_name() {
        return contacts_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.contacts_name
     *
     * @param contacts_name the value for jsh_depothead.contacts_name
     *
     * @mbggenerated
     */
    public void setContacts_name(String contacts_name) {
        this.contacts_name = contacts_name == null ? null : contacts_name.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.we_chat
     *
     * @return the value of jsh_depothead.we_chat
     *
     * @mbggenerated
     */
    public String getWe_chat() {
        return we_chat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.we_chat
     *
     * @param we_chat the value for jsh_depothead.we_chat
     *
     * @mbggenerated
     */
    public void setWe_chat(String we_chat) {
        this.we_chat = we_chat == null ? null : we_chat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.Id
     *
     * @return the value of jsh_depothead.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.Id
     *
     * @param id the value for jsh_depothead.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.Type
     *
     * @return the value of jsh_depothead.Type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.Type
     *
     * @param type the value for jsh_depothead.Type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.SubType
     *
     * @return the value of jsh_depothead.SubType
     *
     * @mbggenerated
     */
    public String getSubtype() {
        return subtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.SubType
     *
     * @param subtype the value for jsh_depothead.SubType
     *
     * @mbggenerated
     */
    public void setSubtype(String subtype) {
        this.subtype = subtype == null ? null : subtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.ProjectId
     *
     * @return the value of jsh_depothead.ProjectId
     *
     * @mbggenerated
     */
    public Long getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.ProjectId
     *
     * @param projectid the value for jsh_depothead.ProjectId
     *
     * @mbggenerated
     */
    public void setProjectid(Long projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.DefaultNumber
     *
     * @return the value of jsh_depothead.DefaultNumber
     *
     * @mbggenerated
     */
    public String getDefaultnumber() {
        return defaultnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.DefaultNumber
     *
     * @param defaultnumber the value for jsh_depothead.DefaultNumber
     *
     * @mbggenerated
     */
    public void setDefaultnumber(String defaultnumber) {
        this.defaultnumber = defaultnumber == null ? null : defaultnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.Number
     *
     * @return the value of jsh_depothead.Number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.Number
     *
     * @param number the value for jsh_depothead.Number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.OperPersonName
     *
     * @return the value of jsh_depothead.OperPersonName
     *
     * @mbggenerated
     */
    public String getOperpersonname() {
        return operpersonname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.OperPersonName
     *
     * @param operpersonname the value for jsh_depothead.OperPersonName
     *
     * @mbggenerated
     */
    public void setOperpersonname(String operpersonname) {
        this.operpersonname = operpersonname == null ? null : operpersonname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.CreateTime
     *
     * @return the value of jsh_depothead.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.CreateTime
     *
     * @param createtime the value for jsh_depothead.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.OperTime
     *
     * @return the value of jsh_depothead.OperTime
     *
     * @mbggenerated
     */
    public Date getOpertime() {
        return opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.OperTime
     *
     * @param opertime the value for jsh_depothead.OperTime
     *
     * @mbggenerated
     */
    public void setOpertime(Date opertime) {
        this.opertime = opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.OrganId
     *
     * @return the value of jsh_depothead.OrganId
     *
     * @mbggenerated
     */
    public Long getOrganid() {
        return organid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.OrganId
     *
     * @param organid the value for jsh_depothead.OrganId
     *
     * @mbggenerated
     */
    public void setOrganid(Long organid) {
        this.organid = organid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.HandsPersonId
     *
     * @return the value of jsh_depothead.HandsPersonId
     *
     * @mbggenerated
     */
    public Long getHandspersonid() {
        return handspersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.HandsPersonId
     *
     * @param handspersonid the value for jsh_depothead.HandsPersonId
     *
     * @mbggenerated
     */
    public void setHandspersonid(Long handspersonid) {
        this.handspersonid = handspersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.AccountId
     *
     * @return the value of jsh_depothead.AccountId
     *
     * @mbggenerated
     */
    public Long getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.AccountId
     *
     * @param accountid the value for jsh_depothead.AccountId
     *
     * @mbggenerated
     */
    public void setAccountid(Long accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.ChangeAmount
     *
     * @return the value of jsh_depothead.ChangeAmount
     *
     * @mbggenerated
     */
    public BigDecimal getChangeamount() {
        return changeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.ChangeAmount
     *
     * @param changeamount the value for jsh_depothead.ChangeAmount
     *
     * @mbggenerated
     */
    public void setChangeamount(BigDecimal changeamount) {
        this.changeamount = changeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.AllocationProjectId
     *
     * @return the value of jsh_depothead.AllocationProjectId
     *
     * @mbggenerated
     */
    public Long getAllocationprojectid() {
        return allocationprojectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.AllocationProjectId
     *
     * @param allocationprojectid the value for jsh_depothead.AllocationProjectId
     *
     * @mbggenerated
     */
    public void setAllocationprojectid(Long allocationprojectid) {
        this.allocationprojectid = allocationprojectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.TotalPrice
     *
     * @return the value of jsh_depothead.TotalPrice
     *
     * @mbggenerated
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.TotalPrice
     *
     * @param totalprice the value for jsh_depothead.TotalPrice
     *
     * @mbggenerated
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.PayType
     *
     * @return the value of jsh_depothead.PayType
     *
     * @mbggenerated
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.PayType
     *
     * @param paytype the value for jsh_depothead.PayType
     *
     * @mbggenerated
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype == null ? null : paytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.Remark
     *
     * @return the value of jsh_depothead.Remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.Remark
     *
     * @param remark the value for jsh_depothead.Remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.Salesman
     *
     * @return the value of jsh_depothead.Salesman
     *
     * @mbggenerated
     */
    public String getSalesman() {
        return salesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.Salesman
     *
     * @param salesman the value for jsh_depothead.Salesman
     *
     * @mbggenerated
     */
    public void setSalesman(String salesman) {
        this.salesman = salesman == null ? null : salesman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.AccountIdList
     *
     * @return the value of jsh_depothead.AccountIdList
     *
     * @mbggenerated
     */
    public String getAccountidlist() {
        return accountidlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.AccountIdList
     *
     * @param accountidlist the value for jsh_depothead.AccountIdList
     *
     * @mbggenerated
     */
    public void setAccountidlist(String accountidlist) {
        this.accountidlist = accountidlist == null ? null : accountidlist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.AccountMoneyList
     *
     * @return the value of jsh_depothead.AccountMoneyList
     *
     * @mbggenerated
     */
    public String getAccountmoneylist() {
        return accountmoneylist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.AccountMoneyList
     *
     * @param accountmoneylist the value for jsh_depothead.AccountMoneyList
     *
     * @mbggenerated
     */
    public void setAccountmoneylist(String accountmoneylist) {
        this.accountmoneylist = accountmoneylist == null ? null : accountmoneylist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.Discount
     *
     * @return the value of jsh_depothead.Discount
     *
     * @mbggenerated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.Discount
     *
     * @param discount the value for jsh_depothead.Discount
     *
     * @mbggenerated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.DiscountMoney
     *
     * @return the value of jsh_depothead.DiscountMoney
     *
     * @mbggenerated
     */
    public BigDecimal getDiscountmoney() {
        return discountmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.DiscountMoney
     *
     * @param discountmoney the value for jsh_depothead.DiscountMoney
     *
     * @mbggenerated
     */
    public void setDiscountmoney(BigDecimal discountmoney) {
        this.discountmoney = discountmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.DiscountLastMoney
     *
     * @return the value of jsh_depothead.DiscountLastMoney
     *
     * @mbggenerated
     */
    public BigDecimal getDiscountlastmoney() {
        return discountlastmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.DiscountLastMoney
     *
     * @param discountlastmoney the value for jsh_depothead.DiscountLastMoney
     *
     * @mbggenerated
     */
    public void setDiscountlastmoney(BigDecimal discountlastmoney) {
        this.discountlastmoney = discountlastmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.OtherMoney
     *
     * @return the value of jsh_depothead.OtherMoney
     *
     * @mbggenerated
     */
    public BigDecimal getOthermoney() {
        return othermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.OtherMoney
     *
     * @param othermoney the value for jsh_depothead.OtherMoney
     *
     * @mbggenerated
     */
    public void setOthermoney(BigDecimal othermoney) {
        this.othermoney = othermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.OtherMoneyList
     *
     * @return the value of jsh_depothead.OtherMoneyList
     *
     * @mbggenerated
     */
    public String getOthermoneylist() {
        return othermoneylist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.OtherMoneyList
     *
     * @param othermoneylist the value for jsh_depothead.OtherMoneyList
     *
     * @mbggenerated
     */
    public void setOthermoneylist(String othermoneylist) {
        this.othermoneylist = othermoneylist == null ? null : othermoneylist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.OtherMoneyItem
     *
     * @return the value of jsh_depothead.OtherMoneyItem
     *
     * @mbggenerated
     */
    public String getOthermoneyitem() {
        return othermoneyitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.OtherMoneyItem
     *
     * @param othermoneyitem the value for jsh_depothead.OtherMoneyItem
     *
     * @mbggenerated
     */
    public void setOthermoneyitem(String othermoneyitem) {
        this.othermoneyitem = othermoneyitem == null ? null : othermoneyitem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.AccountDay
     *
     * @return the value of jsh_depothead.AccountDay
     *
     * @mbggenerated
     */
    public Integer getAccountday() {
        return accountday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.AccountDay
     *
     * @param accountday the value for jsh_depothead.AccountDay
     *
     * @mbggenerated
     */
    public void setAccountday(Integer accountday) {
        this.accountday = accountday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.Status
     *
     * @return the value of jsh_depothead.Status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.Status
     *
     * @param status the value for jsh_depothead.Status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.LinkNumber
     *
     * @return the value of jsh_depothead.LinkNumber
     *
     * @mbggenerated
     */
    public String getLinknumber() {
        return linknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.LinkNumber
     *
     * @param linknumber the value for jsh_depothead.LinkNumber
     *
     * @mbggenerated
     */
    public void setLinknumber(String linknumber) {
        this.linknumber = linknumber == null ? null : linknumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.tenant_id
     *
     * @return the value of jsh_depothead.tenant_id
     *
     * @mbggenerated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.tenant_id
     *
     * @param tenantId the value for jsh_depothead.tenant_id
     *
     * @mbggenerated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depothead.delete_Flag
     *
     * @return the value of jsh_depothead.delete_Flag
     *
     * @mbggenerated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depothead.delete_Flag
     *
     * @param deleteFlag the value for jsh_depothead.delete_Flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }
}